In [4]:
from package import math

print(math.add(1,2))

3

In [8]:
import json

data = {"name":"varun", "age":12}
jsonformat = json.dumps(data)
print(jsonformat)

{"name": "varun", "age": 12}

In [130]:
import csv


with open('example.csv', mode="w", newline='') as file:
    writer=csv.writer(file)
    writer.writerow(['name', 'age'])
    writer.writerow(['lol',12])

In [20]:
import numpy as np

array1  = np.array([1,2,3,4,5])
print(array1)
print(type(array1))
print(array1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)

In [31]:
array2 = np.array([1,2,3,4,5,6])
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
print(array2.reshape(2,3))

[[1 2 3]
 [4 5 6]]

In [39]:
np.arange(0,11,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [40]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
ape = np.eye(3,2)

In [47]:
print(ape.size)

6

In [49]:
print(ape.dtype)

float64

In [60]:
ape = np.array([1,2,3,45,5,2,3,1,1])
print(ape.size)

9

In [63]:
ape = ape.reshape(3,3)

In [64]:
print(ape)

[[ 1  2  3]
 [45  5  2]
 [ 3  1  1]]

In [65]:
ape.transpose()

array([[ 1, 45,  3],
       [ 2,  5,  1],
       [ 3,  2,  1]])

In [66]:
ape.__invert__

In [67]:
print(ape.__invert__)

<method-wrapper '__invert__' of numpy.ndarray object at 0x10f23be10>

In [68]:
print(ape)

[[ 1  2  3]
 [45  5  2]
 [ 3  1  1]]

In [71]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

print(arr1+arr2)

[2 4 6]

In [74]:
twoDArray = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(twoDArray)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

In [75]:
print(twoDArray[0][1])

1

In [85]:
print(twoDArray[0:2, 2:])

[[2]
 [5]]

In [87]:
data = np.array([1,2,3,4,5,6,7,8,9])
print(data[data>5])

[6 7 8 9]

In [88]:
import pandas as pd

In [90]:
data=[1,2,3,4,5]

series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [91]:
data = {'a':1, 'b':2, 'c':3}
print(data)

{'a': 1, 'b': 2, 'c': 3}

In [92]:
print(pd.Series(data))

a    1
b    2
c    3
dtype: int64

In [96]:
indexes = ["a", "b", "c"]
data = [11,12,13]

combined = pd.Series(data, indexes)

In [97]:
print(combined)

a    11
b    12
c    13
dtype: int64

In [98]:
data = {
    'Name':["John", "Jill", "Jack"],
    'Age':[10,20,30],
    'City':["New York", "California", "Bronx"]
}

dataframe = pd.DataFrame(data)

In [99]:
print(dataframe)

   Name  Age        City
0  John   10    New York
1  Jill   20  California
2  Jack   30       Bronx

In [110]:
youngfly = pd.read_csv("sampledata.csv")

In [112]:
print(youngfly.head(2))

   index  Name  Age         City
0      5  John   28     New York
1      6  Jane   24  Los Angeles

In [114]:
youngfly["Name"]

0    John
1    Jane
2    Jake
3    Jill
Name: Name, dtype: object

In [116]:
youngfly

   index  Name  Age         City
0      5  John   28     New York
1      6  Jane   24  Los Angeles
2      7  Jake   35      Chicago
3      8  Jill   40      Houston

In [125]:
youngfly['salary']=[100,20,30,40]

In [126]:
youngfly

   index  Name  Age         City  salary
0      5  John   28     New York     100
1      6  Jane   24  Los Angeles      20
2      7  Jake   35      Chicago      30
3      8  Jill   40      Houston      40

In [127]:
youngfly.drop("salary", axis=1, inplace=True)

In [123]:
print(youngfly)

   index  Name  Age         City
0      5  John   28     New York
1      6  Jane   24  Los Angeles
2      7  Jake   35      Chicago
3      8  Jill   40      Houston

In [128]:
youngfly["Age"]=youngfly["Age"]+1

In [129]:
print(youngfly)

   index  Name  Age         City
0      5  John   29     New York
1      6  Jane   25  Los Angeles
2      7  Jake   36      Chicago
3      8  Jill   41      Houston